version: '3.2'
services:
  postgres:
    image: "postgres:12"
    logging:
      driver: none 
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

volumes:
  postgres:
